import 'package:flutter/material.dart';

class TaskIcons {

  static const double iconSize = 48;
  static const Color taskIconColor = Color(0xFFFFFFFF);
  
  static const List<Icon> taskIconList = [
    Icon(Icons.access_alarm, color: taskIconColor, size: iconSize),
    Icon(Icons.access_time, color: taskIconColor, size: iconSize),
    Icon(Icons.archive_outlined, color: taskIconColor, size: iconSize),
    Icon(Icons.accessibility, color: taskIconColor, size: iconSize),
    Icon(Icons.add_circle_outline, color: taskIconColor, size: iconSize),
    Icon(Icons.air, color: taskIconColor, size: iconSize),
    Icon(Icons.airplane_ticket_outlined, color: taskIconColor, size: iconSize),
    Icon(Icons.airplanemode_active, color: taskIconColor, size: iconSize),
    Icon(Icons.all_inclusive, color: taskIconColor, size: iconSize),
    Icon(Icons.anchor, color: taskIconColor, size: iconSize),
    Icon(Icons.architecture, color: taskIconColor, size: iconSize),
    Icon(Icons.auto_stories_outlined, color: taskIconColor, size: iconSize),
    Icon(Icons.menu_book, color: taskIconColor, size: iconSize),
    Icon(Icons.bookmark_border, color: taskIconColor, size: iconSize),
    Icon(Icons.baby_changing_station, color: taskIconColor, size: iconSize),
    Icon(Icons.backup_outlined, color: taskIconColor, size: iconSize),
    Icon(Icons.battery_charging_full_outlined, color: taskIconColor, size: iconSize),
    Icon(Icons.beach_access_outlined, color: taskIconColor, size: iconSize),
    Icon(Icons.bedtime_outlined, color: taskIconColor, size: iconSize),
    Icon(Icons.blender_outlined, color: taskIconColor, size: iconSize),
    Icon(Icons.build_sharp, color: taskIconColor, size: iconSize),
    Icon(Icons.pedal_bike, color: taskIconColor, size: iconSize),
    Icon(Icons.book, color: taskIconColor, size: iconSize),
    Icon(Icons.brush, color: taskIconColor, size: iconSize),
    Icon(Icons.format_paint_rounded, color: taskIconColor, size: iconSize),
    Icon(Icons.color_lens_outlined, color: taskIconColor, size: iconSize),
    Icon(Icons.colorize_sharp, color: taskIconColor, size: iconSize),
    Icon(Icons.control_camera, color: taskIconColor, size: iconSize),
    Icon(Icons.data_array_sharp, color: taskIconColor, size: iconSize),
    Icon(Icons.data_object, color: taskIconColor, size: iconSize),
    Icon(Icons.sports_bar_outlined, color: taskIconColor, size: iconSize),
    Icon(Icons.sports_gymnastics, color: taskIconColor, size: iconSize),
    Icon(Icons.sports_esports_outlined, color: taskIconColor, size: iconSize),
    Icon(Icons.sports_motorsports_sharp, color: taskIconColor, size: iconSize),
    Icon(Icons.task_alt, color: taskIconColor, size: iconSize),
    Icon(Icons.done_all, color: taskIconColor, size: iconSize),
    Icon(Icons.dark_mode, color: taskIconColor, size: iconSize),
    Icon(Icons.remove_circle_outline_outlined, color: taskIconColor, size: iconSize),
    Icon(Icons.delete, color: taskIconColor, size: iconSize),
    Icon(Icons.work_outline_outlined, color: taskIconColor, size: iconSize),
    Icon(Icons.mediation, color: taskIconColor, size: iconSize),
    Icon(Icons.music_note, color: taskIconColor, size: iconSize),
    Icon(Icons.dry_cleaning, color: taskIconColor, size: iconSize),
    Icon(Icons.celebration, color: taskIconColor, size: iconSize),
    Icon(Icons.directions_walk, color: taskIconColor, size: iconSize),
    Icon(Icons.wifi_protected_setup, color: taskIconColor, size: iconSize),
    Icon(Icons.laptop, color: taskIconColor, size: iconSize),
    Icon(Icons.markunread_rounded, color: taskIconColor, size: iconSize),
    Icon(Icons.location_pin, color: taskIconColor, size: iconSize),
    Icon(Icons.emoji_events_outlined, color: taskIconColor, size: iconSize),
    Icon(Icons.offline_bolt_outlined, color: taskIconColor, size: iconSize),
  ];
}